# Generated by Django 2.0.2 on 2018-03-06 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation_inspection_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 661239))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 661329))),
            ],
        ),
        migrations.CreateModel(
            name='Language_inspection_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 660297))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 660336))),
            ],
        ),
        migrations.CreateModel(
            name='Scene_quality_inspection_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 662860))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 662932))),
            ],
        ),
        migrations.CreateModel(
            name='Sound_quality_inspection_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_quality', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 659256))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 659295))),
            ],
        ),
        migrations.CreateModel(
            name='Video_quality_inspection_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_quality', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 658099))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 15, 5, 658159))),
            ],
        ),
        migrations.RemoveField(
            model_name='video_inspection_vote',
            name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='passed',
            new_name='conversation_passed',
        ),
        migrations.AddField(
            model_name='video',
            name='language_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='scene_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='sound_quality_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='video_quality_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Video_inspection_vote',
        ),
        migrations.AddField(
            model_name='video_quality_inspection_vote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Video'),
        ),
        migrations.AddField(
            model_name='sound_quality_inspection_vote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Video'),
        ),
        migrations.AddField(
            model_name='scene_quality_inspection_vote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Video'),
        ),
        migrations.AddField(
            model_name='language_inspection_vote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Video'),
        ),
        migrations.AddField(
            model_name='conversation_inspection_vote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Video'),
        ),
    ]
