# Generated by Django 2.0.2 on 2018-03-06 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_auto_20180306_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene_inspection_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 698432))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 698473))),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='scene_quality_inspection_vote',
            name='video',
        ),
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 697394)),
        ),
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 697338)),
        ),
        migrations.AlterField(
            model_name='language_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 695715)),
        ),
        migrations.AlterField(
            model_name='language_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 695633)),
        ),
        migrations.AlterField(
            model_name='sound_quality_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 694311)),
        ),
        migrations.AlterField(
            model_name='sound_quality_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 694254)),
        ),
        migrations.AlterField(
            model_name='video_quality_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 692986)),
        ),
        migrations.AlterField(
            model_name='video_quality_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 16, 12, 692925)),
        ),
        migrations.DeleteModel(
            name='Scene_quality_inspection_vote',
        ),
    ]
