# Generated by Django 2.0.2 on 2018-03-06 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0003_auto_20180306_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation_inspection_vote',
            name='batch_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='language_inspection_vote',
            name='batch_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scene_inspection_vote',
            name='batch_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sound_quality_inspection_vote',
            name='batch_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video_quality_inspection_vote',
            name='batch_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 355330)),
        ),
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 355292)),
        ),
        migrations.AlterField(
            model_name='language_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 354037)),
        ),
        migrations.AlterField(
            model_name='language_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 353971)),
        ),
        migrations.AlterField(
            model_name='scene_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 356316)),
        ),
        migrations.AlterField(
            model_name='scene_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 356279)),
        ),
        migrations.AlterField(
            model_name='sound_quality_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 352214)),
        ),
        migrations.AlterField(
            model_name='sound_quality_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 352164)),
        ),
        migrations.AlterField(
            model_name='video_quality_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 350459)),
        ),
        migrations.AlterField(
            model_name='video_quality_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 37, 18, 350404)),
        ),
    ]
