# Generated by Django 2.0.2 on 2018-03-07 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0006_auto_20180306_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 0, 9, 42)),
        ),
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 0, 9, 42)),
        ),
    ]
