# Generated by Django 2.0.2 on 2018-03-07 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0007_auto_20180307_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='conversation_inspection_vote',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
