# Generated by Django 2.0.2 on 2018-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0008_auto_20180307_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation_inspection_vote',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='conversation_inspection_vote',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversation_inspection_vote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='conversation_inspection_vote',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='conversation_inspection_vote',
            name='video',
        ),
        migrations.RemoveField(
            model_name='language_inspection_vote',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='language_inspection_vote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='language_inspection_vote',
            name='language',
        ),
        migrations.RemoveField(
            model_name='language_inspection_vote',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='language_inspection_vote',
            name='video',
        ),
        migrations.RemoveField(
            model_name='scene_inspection_vote',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='scene_inspection_vote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='scene_inspection_vote',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='scene_inspection_vote',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='scene_inspection_vote',
            name='video',
        ),
        migrations.RemoveField(
            model_name='sound_quality_inspection_vote',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='sound_quality_inspection_vote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sound_quality_inspection_vote',
            name='sound_quality',
        ),
        migrations.RemoveField(
            model_name='sound_quality_inspection_vote',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='sound_quality_inspection_vote',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video_quality_inspection_vote',
            name='video_quality',
        ),
        migrations.AddField(
            model_name='video_quality_inspection_vote',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
    ]
