# Generated by Django 2.0.2 on 2018-03-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0010_auto_20180307_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation_inspection_vote',
            name='w_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='language_inspection_vote',
            name='w_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scene_inspection_vote',
            name='w_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sound_quality_inspection_vote',
            name='w_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video_quality_inspection_vote',
            name='w_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
