# Generated by Django 2.0.2 on 2018-03-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_label_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0)),
                ('valence', models.IntegerField(default=0)),
                ('arousal', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=50)),
                ('reasoning', models.TextField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='', max_length=200)),
                ('video_url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion_label_experiment',
            fields=[
                ('emotion_label_meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emotion_labeling.Emotion_label_Meta')),
                ('experiment_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Experiment_Video')),
            ],
            bases=('emotion_labeling.emotion_label_meta',),
        ),
    ]
