# Generated by Django 2.0.2 on 2018-03-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0002_experiment_video_video_prompt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_label_meta',
            name='aid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='wid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
