# Generated by Django 2.0.2 on 2018-03-21 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0004_emotion_check_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_label_meta',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
