# Generated by Django 2.0.2 on 2018-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0005_emotion_label_meta_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_label_meta',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
