# Generated by Django 2.0.2 on 2018-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0007_emotion_label_experiment_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_label_meta',
            name='angry_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='depressed_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='disgusted_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='excited_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='fearful_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='frustrated_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='happy_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='neutral_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='other_m',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='sad_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_label_meta',
            name='surprised_m',
            field=models.BooleanField(default=False),
        ),
    ]
