# Generated by Django 2.0.2 on 2018-03-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0009_emotion_label_component_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion_label_component_process',
            old_name='cognitive',
            new_name='cog_motiv',
        ),
        migrations.RemoveField(
            model_name='emotion_label_component_process',
            name='motivational',
        ),
    ]
