# Generated by Django 2.0.2 on 2018-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0011_emotion_label_component_process_likert'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_label_component_process_likert',
            name='not_sure_reasoning',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
