# Generated by Django 2.0.2 on 2018-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0012_emotion_label_component_process_likert_not_sure_reasoning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus_Paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('hid', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='experiment_video',
            name='video_img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
