# Generated by Django 2.0.2 on 2018-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0013_auto_20180411_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_video',
            name='video_url',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
