# Generated by Django 2.0.2 on 2018-04-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0014_auto_20180411_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_video',
            name='video_prompt_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment_video',
            name='video_total_time',
            field=models.IntegerField(default=0),
        ),
    ]
