# Generated by Django 2.0.2 on 2018-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0015_auto_20180412_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Before_Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='', max_length=200)),
                ('video_url', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
