# Generated by Django 2.0.2 on 2018-05-02 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0018_emotion_label_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_Label_Component_Process_Only',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiling', models.IntegerField(default=1)),
                ('mouth_close_open', models.IntegerField(default=3)),
                ('mouth_tensing', models.IntegerField(default=1)),
                ('frowning', models.IntegerField(default=1)),
                ('tear', models.IntegerField(default=1)),
                ('eyes_close_open', models.IntegerField(default=3)),
                ('volume_volume', models.IntegerField(default=3)),
                ('voice_trembling', models.IntegerField(default=1)),
                ('voice_assertive', models.IntegerField(default=3)),
                ('body_abrupt', models.IntegerField(default=1)),
                ('towards', models.IntegerField(default=1)),
                ('withdrawing', models.IntegerField(default=1)),
                ('against', models.IntegerField(default=1)),
                ('utterance_length', models.IntegerField(default=3)),
                ('speech_melody', models.IntegerField(default=1)),
                ('speech_disturbed', models.IntegerField(default=1)),
                ('speech_tempo', models.IntegerField(default=3)),
                ('shiver', models.IntegerField(default=1)),
                ('pale', models.IntegerField(default=1)),
                ('breathing', models.IntegerField(default=3)),
                ('sweating', models.IntegerField(default=1)),
                ('blushing', models.IntegerField(default=1)),
                ('sudden', models.IntegerField(default=1)),
                ('probable', models.IntegerField(default=1)),
                ('pleasant', models.IntegerField(default=1)),
                ('chance', models.IntegerField(default=1)),
                ('own', models.IntegerField(default=1)),
                ('other', models.IntegerField(default=1)),
                ('intentionally', models.IntegerField(default=1)),
                ('norm', models.IntegerField(default=1)),
                ('goal', models.IntegerField(default=1)),
                ('expected', models.IntegerField(default=1)),
                ('consistency', models.IntegerField(default=1)),
                ('envisaged', models.IntegerField(default=1)),
                ('consequence', models.IntegerField(default=1)),
                ('immediate', models.IntegerField(default=1)),
                ('avoidable', models.IntegerField(default=1)),
                ('adjustable', models.IntegerField(default=1)),
                ('attention_event', models.IntegerField(default=1)),
                ('searching_info', models.IntegerField(default=1)),
                ('attention_people', models.IntegerField(default=1)),
                ('physical_event', models.IntegerField(default=1)),
                ('not_sure_reasoning', models.CharField(default='', max_length=1000)),
                ('experiment_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Experiment_Video')),
            ],
        ),
    ]
