# Generated by Django 2.0.2 on 2018-05-02 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0019_emotion_label_component_process_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_label_component_process_only',
            name='aid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='emotion_label_component_process_only',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emotion_label_component_process_only',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotion_label_component_process_only',
            name='wid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
