# Generated by Django 2.0.2 on 2018-05-16 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0021_emotion_distribution_collection_emotion_distribution_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion_distribution_meta',
            name='experiment_video',
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='aid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='distribution',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='experiment_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Experiment_Video'),
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotion_distribution_collection',
            name='wid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Emotion_Distribution_Meta',
        ),
    ]
