# Generated by Django 2.0.2 on 2018-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0022_auto_20180516_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_video',
            name='video_hit_dict',
            field=models.CharField(default='', max_length=200000, null=True),
        ),
    ]
