# Generated by Django 2.0.2 on 2018-05-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0023_auto_20180517_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_Distribution_Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('distribution', models.CharField(default='', max_length=20000)),
            ],
        ),
        migrations.AlterField(
            model_name='experiment_video',
            name='video_hit_dict',
            field=models.CharField(blank=True, default='', max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='emotion_distribution_example',
            name='experiment_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Experiment_Video'),
        ),
    ]
