# Generated by Django 2.0.2 on 2018-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0024_auto_20180530_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='', max_length=200)),
                ('video_url', models.CharField(default='', max_length=2000)),
                ('video_img', models.CharField(default='', max_length=200)),
                ('video_prompt_time', models.IntegerField(default=0)),
            ],
        ),
    ]
