# Generated by Django 2.0.2 on 2018-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0025_study_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(default='', max_length=200)),
                ('frame_definition', models.CharField(default='', max_length=20000)),
            ],
        ),
    ]
