# Generated by Django 2.0.2 on 2018-06-16 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0026_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Frame_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_sub_id', models.IntegerField(default='-1')),
                ('frame_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence')),
            ],
        ),
    ]
