# Generated by Django 2.0.2 on 2018-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0027_frame_sentence_frame_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame_task',
            old_name='result',
            new_name='frame_confidences',
        ),
        migrations.AddField(
            model_name='frame_task',
            name='no_reason_field',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
