# Generated by Django 2.0.2 on 2018-06-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0028_auto_20180616_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame_task',
            old_name='no_reason_field',
            new_name='no_field_reasoning',
        ),
    ]
