# Generated by Django 2.0.2 on 2018-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0029_auto_20180616_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame_Task_Checkbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Frame_Task_Checkbox_Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Frame_Task_Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='frame_task',
            name='frame_sentence',
        ),
        migrations.DeleteModel(
            name='Frame_Task',
        ),
    ]
