# Generated by Django 2.0.2 on 2018-06-18 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0030_auto_20180618_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='aid',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='frame_confidences',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='frame_sentence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence'),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='no_field_reasoning',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='task_sub_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='wid',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='aid',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='frame_confidences',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='frame_sentence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence'),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='no_field_reasoning',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='task_sub_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='wid',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='aid',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='frame_confidences',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='frame_sentence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence'),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='no_field_reasoning',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='task_sub_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='wid',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
