# Generated by Django 2.0.2 on 2018-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0031_auto_20180618_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_task_checkbox',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='frame_task_checkbox_confidence',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='frame_task_radio',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
