# Generated by Django 2.0.2 on 2018-06-20 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0033_auto_20180618_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame_Task_Radio_Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('frame_confidences', models.CharField(default='', max_length=20000)),
                ('no_field_reasoning', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_sub_id', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('survey_result', models.CharField(default='', max_length=20000)),
                ('frame_sentence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
