# Generated by Django 2.0.2 on 2018-06-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0035_frame_gold_data_checkbox_frame_gold_data_checkbox_confidence_frame_sentence_gt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_gold_data_checkbox',
            name='frame_sentence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence_GT'),
        ),
        migrations.AlterField(
            model_name='frame_gold_data_checkbox_confidence',
            name='frame_sentence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence_GT'),
        ),
    ]
