# Generated by Django 2.0.2 on 2018-07-04 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0036_auto_20180629_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_Task_Checkbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_confidences', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_time', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('survey_result', models.CharField(default='', max_length=20000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion_Task_Checkbox_Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_confidences', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_time', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('survey_result', models.CharField(default='', max_length=20000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion_Task_Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_confidences', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_time', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('survey_result', models.CharField(default='', max_length=20000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion_Task_Radio_Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_confidences', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_time', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('survey_result', models.CharField(default='', max_length=20000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='', max_length=200)),
                ('video_url', models.CharField(default='', max_length=2000)),
                ('video_img', models.CharField(default='', max_length=200)),
                ('video_prompt_time', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='emotion_task_radio_confidence',
            name='emotion_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Emotion_Video'),
        ),
        migrations.AddField(
            model_name='emotion_task_radio',
            name='emotion_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Emotion_Video'),
        ),
        migrations.AddField(
            model_name='emotion_task_checkbox_confidence',
            name='emotion_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Emotion_Video'),
        ),
        migrations.AddField(
            model_name='emotion_task_checkbox',
            name='emotion_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Emotion_Video'),
        ),
    ]
