# Generated by Django 2.0.2 on 2018-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0037_auto_20180704_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_task_checkbox',
            name='other',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='emotion_task_checkbox_confidence',
            name='other',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='emotion_task_radio',
            name='other',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='emotion_task_radio_confidence',
            name='other',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
