# Generated by Django 2.1.2 on 2018-10-16 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0039_emotion_gold_data_checkbox_emotion_gold_data_checkbox_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion_Gold_Data_Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_confidences', models.CharField(default='', max_length=20000)),
                ('other', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_time', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('emotion_video', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Emotion_Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion_Gold_Data_Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('emotion_confidences', models.CharField(default='', max_length=20000)),
                ('other', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_time', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('emotion_video', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Emotion_Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frame_Gold_Data_Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
                ('frame_confidences', models.CharField(default='', max_length=20000)),
                ('no_field_reasoning', models.CharField(default='', max_length=20000)),
                ('wid', models.CharField(default='', max_length=2000)),
                ('aid', models.CharField(default='', max_length=2000)),
                ('task_sub_id', models.IntegerField(default='-1')),
                ('token', models.CharField(default='', max_length=200)),
                ('frame_sentence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emotion_labeling.Frame_Sentence_GT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
