# Generated by Django 2.1.2 on 2018-10-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_labeling', '0040_emotion_gold_data_distribution_emotion_gold_data_radio_frame_gold_data_radio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion_gold_data_distribution',
            name='emotion_video',
        ),
        migrations.DeleteModel(
            name='Emotion_Gold_Data_Distribution',
        ),
    ]
